### ISSUE TITLE
list CLDF paper in bibliography

### ISSUE THREAD

**Issue by xrotwang** [digitallinguistics/digitallinguistics.io#170]
You may want to include our 2018 paper [Cross-Linguistic Data Formats, advancing data sharing and re-use in comparative linguistics](https://dx.doi.org/10.1038/sdata.2018.205) to your bibliography.

**Comment by dwhieb** [comment]
This one's already on the list to add! Thank you!

**Comment by dwhieb** [comment]
Moving all bibliography items to a separate Trello board. Closing this issue.
